added -validate to Entry / fixed: Fileselect scanning from listbox dropped files / fixed: -autoscale in chart dialogs / fixed: stack trace used to set global w / Entry: labelcolor is seperate option ...

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -12,9 +12,9 @@ ac_help=
 ac_default_prefix=/usr/local
 # Any additions from configure.in:
 ac_help="$ac_help
-  --with-tcl=DIR          Use Tcl 8.0 source tree from DIR"
+  --with-tclconfigdir=DIR	Use tclConfig.sh from DIR"
 ac_help="$ac_help
-  --with-tk=DIR          use Tk 8.0 source tree from DIR"
+  --with-tkconfigdir=DIR	Use tkConfig.sh from DIR"
 
 # Initialize some variables set by options.
 # The variables have the same names as the options, with
@@ -524,45 +524,45 @@ fi
 
 # SCCS: @(#) configure.in 1.9 96/04/15 09:50:20
 
-#--------------------------------------------------------------------
-#	See if there was a command-line option for where Tcl is;  if
-#	not, assume that its top-level directory is a sibling of ours.
-#--------------------------------------------------------------------
+if test "${prefix}" = "NONE"; then
+    prefix=/usr/local
+    echo "setting prefix to: ${prefix}"
+fi
+if test "${exec_prefix}" = "NONE"; then
+    exec_prefix=$prefix
+    echo "setting exec-prefix to: ${exec_prefix}"
+fi
 
-# Check whether --with-tcl or --without-tcl was given.
-if test "${with_tcl+set}" = set; then
-  withval="$with_tcl"
-  TCL_SRC_DIR=$withval
+# Check whether --with-tclconfigdir or --without-tclconfigdir was given.
+if test "${with_tclconfigdir+set}" = set; then
+  withval="$with_tclconfigdir"
+  TCL_CONFIG_DIR=$withval
 else
-  TCL_SRC_DIR=`cd ../../tcl8.0; pwd`
+  TCL_CONFIG_DIR=`cd ${exec_prefix}/lib; pwd`
 fi
 
-if test ! -d $TCL_SRC_DIR; then
-    { echo "configure: error: Tcl directory $TCL_SRC_DIR doesn't exist" 1>&2; exit 1; }
-fi
-
-# Check whether --with-tk or --without-tk was given.
-if test "${with_tk+set}" = set; then
-  withval="$with_tk"
-  TK_SRC_DIR=$withval
+# Check whether --with-tkconfigdir or --without-tkconfigdir was given.
+if test "${with_tkconfigdir+set}" = set; then
+  withval="$with_tkconfigdir"
+  TK_CONFIG_DIR=$withval
 else
-  TK_SRC_DIR=`cd $TCL_SRC_DIR/../tk8.0; pwd`
+  TK_CONFIG_DIR=`cd $TCL_CONFIG_DIR; pwd`
 fi
 
-if test ! -d $TK_SRC_DIR; then
-    { echo "configure: error: Tcl directory $TK_SRC_DIR doesn't exist" 1>&2; exit 1; }
+
+if test ! -f $TCL_CONFIG_DIR/tclConfig.sh; then
+	{ echo "configure: error: $TCL_CONFIG_DIR/tclConfig.sh not found" 1>&2; exit 1; }
 fi
-
-#--------------------------------------------------------------------
-#	Read in configuration information generated by Tcl for shared
-#	libraries, and arrange for it to be substituted into our
-#	Makefile.
-#--------------------------------------------------------------------
-
-file=$TCL_SRC_DIR/unix/tclConfig.sh
+if test ! -f $TK_CONFIG_DIR/tkConfig.sh; then
+	{ echo "configure: error: $TK_CONFIG_DIR/tkConfig.sh not found" 1>&2; exit 1; }
+fi
+echo "Using $TCL_CONFIG_DIR/tclConfig.sh"
+echo "Using $TK_CONFIG_DIR/tkConfig.sh"
+file=$TCL_CONFIG_DIR/tclConfig.sh
 . $file
-file=$TK_SRC_DIR/unix/tkConfig.sh
+file=$TK_CONFIG_DIR/tkConfig.sh
 . $file
+
 CC=$TCL_CC
 SHLIB_CFLAGS=$TCL_SHLIB_CFLAGS
 SHLIB_LD=$TCL_SHLIB_LD
@@ -858,6 +858,4 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
-
-
 
